// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdiloietghwftizkwthx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkaWxvaWV0Z2h3ZnRpemt3dGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzg0MjUsImV4cCI6MjA2NTY1NDQyNX0.3Gnh-stubwvkkIGebPi4vA_GbgDe5pf6lGiByCljh0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);